mkdir -p /root/123/npm/hexo-theme-butterfly@4.2.2/source/js  &&   cd /root/123/npm/hexo-theme-butterfly@4.2.2/source/js && wget https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@4.2.2/source/js/main.min.js
mkdir -p /root/123/npm/hexo-theme-butterfly@4.2.2/source/js  &&   cd /root/123/npm/hexo-theme-butterfly@4.2.2/source/js && wget https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@4.2.2/source/js/utils.min.js
mkdir -p /root/123/npm/hexo-theme-butterfly@4.2.2/source/js  &&   cd /root/123/npm/hexo-theme-butterfly@4.2.2/source/js && wget https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@4.2.2/source/js/tw_cn.min.js
mkdir -p /root/123/npm/hexo-theme-butterfly@4.2.2/source/js/search  &&   cd /root/123/npm/hexo-theme-butterfly@4.2.2/source/js/search && wget https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@4.2.2/source/js/search/local-search.min.js
mkdir -p /root/123/npm/hexo-theme-butterfly@4.2.2/source/js/search  &&   cd /root/123/npm/hexo-theme-butterfly@4.2.2/source/js/search && wget https://cdn.jsdelivr.net/npm/hexo-theme-butterfly@4.2.2/source/js/search/algolia.min.js
mkdir -p /root/123/npm/algoliasearch@4/dist  &&   cd /root/123/npm/algoliasearch@4/dist && wget https://cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
mkdir -p /root/123/npm/instantsearch.js@4/dist  &&   cd /root/123/npm/instantsearch.js@4/dist && wget https://cdn.jsdelivr.net/npm/instantsearch.js@4/dist/instantsearch.production.min.js
mkdir -p /root/123/npm/pjax  &&   cd /root/123/npm/pjax && wget https://cdn.jsdelivr.net/npm/pjax/pjax.min.js
mkdir -p /root/123/npm/gitalk@latest/dist  &&   cd /root/123/npm/gitalk@latest/dist && wget https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
mkdir -p /root/123/npm/gitalk/dist  &&   cd /root/123/npm/gitalk/dist && wget https://cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.css
mkdir -p /root/123/npm/blueimp-md5/js  &&   cd /root/123/npm/blueimp-md5/js && wget https://cdn.jsdelivr.net/npm/blueimp-md5/js/md5.min.js
mkdir -p /root/123/npm/valine/dist  &&   cd /root/123/npm/valine/dist && wget https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js
mkdir -p /root/123/npm/disqusjs@1/dist  &&   cd /root/123/npm/disqusjs@1/dist && wget https://cdn.jsdelivr.net/npm/disqusjs@1/dist/disqus.js
mkdir -p /root/123/npm/disqusjs@1/dist  &&   cd /root/123/npm/disqusjs@1/dist && wget https://cdn.jsdelivr.net/npm/disqusjs@1/dist/disqusjs.css
mkdir -p /root/123/npm/twikoo@1/dist  &&   cd /root/123/npm/twikoo@1/dist && wget https://cdn.jsdelivr.net/npm/twikoo@1/dist/twikoo.all.min.js
mkdir -p /root/123/npm/@waline/client/dist  &&   cd /root/123/npm/@waline/client/dist && wget https://cdn.jsdelivr.net/npm/@waline/client/dist/waline.js
mkdir -p /root/123/npm/@waline/client/dist  &&   cd /root/123/npm/@waline/client/dist && wget https://cdn.jsdelivr.net/npm/@waline/client/dist/waline.css
mkdir -p /root/123/gh/overtrue/share.js@master/dist/js  &&   cd /root/123/gh/overtrue/share.js@master/dist/js && wget https://cdn.jsdelivr.net/gh/overtrue/share.js@master/dist/js/social-share.min.js
mkdir -p /root/123/npm/social-share.js/dist/css  &&   cd /root/123/npm/social-share.js/dist/css && wget https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css
mkdir -p /root/123/npm/mathjax@3/es5  &&   cd /root/123/npm/mathjax@3/es5 && wget https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
mkdir -p /root/123/npm/katex@latest/dist  &&   cd /root/123/npm/katex@latest/dist && wget https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
mkdir -p /root/123/npm/katex@latest/dist/contrib  &&   cd /root/123/npm/katex@latest/dist/contrib && wget https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.js
mkdir -p /root/123/npm/katex@latest/dist/contrib  &&   cd /root/123/npm/katex@latest/dist/contrib && wget https://cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.css
mkdir -p /root/123/npm/mermaid/dist  &&   cd /root/123/npm/mermaid/dist && wget https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-ribbon.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-fluttering-ribbon.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/canvas-nest.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/activate-power-mode.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/fireworks.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/click-heart.min.js
mkdir -p /root/123/npm/butterfly-extsrc@1/dist  &&   cd /root/123/npm/butterfly-extsrc@1/dist && wget https://cdn.jsdelivr.net/npm/butterfly-extsrc@1/dist/click-show-text.min.js
mkdir -p /root/123/npm/vanilla-lazyload/dist  &&   cd /root/123/npm/vanilla-lazyload/dist && wget https://cdn.jsdelivr.net/npm/vanilla-lazyload/dist/lazyload.iife.min.js
mkdir -p /root/123/npm/instant.page@5  &&   cd /root/123/npm/instant.page@5 && wget https://cdn.jsdelivr.net/npm/instant.page@5/instantpage.min.js
mkdir -p /root/123/npm/typed.js/lib  &&   cd /root/123/npm/typed.js/lib && wget https://cdn.jsdelivr.net/npm/typed.js/lib/typed.min.js
mkdir -p /root/123/npm/pangu@4/dist/browser  &&   cd /root/123/npm/pangu@4/dist/browser && wget https://cdn.jsdelivr.net/npm/pangu@4/dist/browser/pangu.min.js
mkdir -p /root/123/npm/@fancyapps/ui/dist  &&   cd /root/123/npm/@fancyapps/ui/dist && wget https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.css
mkdir -p /root/123/npm/@fancyapps/ui/dist  &&   cd /root/123/npm/@fancyapps/ui/dist && wget https://cdn.jsdelivr.net/npm/@fancyapps/ui/dist/fancybox.umd.js
mkdir -p /root/123/npm/medium-zoom/dist  &&   cd /root/123/npm/medium-zoom/dist && wget https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js
mkdir -p /root/123/npm/node-snackbar/dist  &&   cd /root/123/npm/node-snackbar/dist && wget https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css
mkdir -p /root/123/npm/node-snackbar/dist  &&   cd /root/123/npm/node-snackbar/dist && wget https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/css  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/css && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/css/all.min.css
mkdir -p /root/123/npm/flickr-justified-gallery@2/dist  &&   cd /root/123/npm/flickr-justified-gallery@2/dist && wget https://cdn.jsdelivr.net/npm/flickr-justified-gallery@2/dist/fjGallery.min.js
mkdir -p /root/123/npm/flickr-justified-gallery@2/dist  &&   cd /root/123/npm/flickr-justified-gallery@2/dist && wget https://cdn.jsdelivr.net/npm/flickr-justified-gallery@2/dist/fjGallery.min.css
mkdir -p /root/123/npm/aplayer@1/dist  &&   cd /root/123/npm/aplayer@1/dist && wget https://cdn.jsdelivr.net/npm/aplayer@1/dist/APlayer.min.css
mkdir -p /root/123/npm/aplayer@1/dist  &&   cd /root/123/npm/aplayer@1/dist && wget https://cdn.jsdelivr.net/npm/aplayer@1/dist/APlayer.min.js
mkdir -p /root/123/gh/metowolf/MetingJS@1.2/dist  &&   cd /root/123/gh/metowolf/MetingJS@1.2/dist && wget https://cdn.jsdelivr.net/gh/metowolf/MetingJS@1.2/dist/Meting.min.js
mkdir -p /root/123/npm/prismjs@1  &&   cd /root/123/npm/prismjs@1 && wget https://cdn.jsdelivr.net/npm/prismjs@1/prism.min.js
mkdir -p /root/123/npm/prismjs@1/plugins/line-numbers  &&   cd /root/123/npm/prismjs@1/plugins/line-numbers && wget https://cdn.jsdelivr.net/npm/prismjs@1/plugins/line-numbers/prism-line-numbers.min.js
mkdir -p /root/123/npm/prismjs@1/plugins/autoloader  &&   cd /root/123/npm/prismjs@1/plugins/autoloader && wget https://cdn.jsdelivr.net/npm/prismjs@1/plugins/autoloader/prism-autoloader.min.js
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/webfonts  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/webfonts && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/webfonts/fa-solid-900.ttf
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/webfonts  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/webfonts && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/webfonts/fa-solid-900.woff2
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/webfonts  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/webfonts && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/webfonts/fa-regular-400.ttf
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/webfonts  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/webfonts && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/webfonts/fa-regular-400.woff2
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/webfonts  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/webfonts && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/webfonts/fa-brands-400.ttf
mkdir -p /root/123/npm/@fortawesome/fontawesome-free@6/webfonts  &&   cd /root/123/npm/@fortawesome/fontawesome-free@6/webfonts && wget https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6/webfonts/fa-brands-400.woff2
